[tool.poetry]
name = "RozetkaScrapeAPI"
version = "0.1.0"
description = ""
authors = ["github.com/AnyoneClown"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
